import clientPromise from "@/lib/mongodb";
import Head from "next/head";
import Image from "next/image";

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}

// export async function getServerSideProps() {
//   const client = await clientPromise;
//   const db = client.db("database_name");
//   const data = await db.collection("collection_name").find({}).toArray();
//   return { data: data };
// }
